name: CI

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Lua & Luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          luarocks install luacheck
      - name: Run luacheck
        run: luacheck ./
