name: Upload new release

on:
  push:
    branches:
      - "main"

jobs:

  Validate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Get previous version
        id: get_previous_version
        run: |
          pip install jq
          git fetch origin main
          prev_version=$(git show origin/main:info.json | jq -r '.version')
          echo "version=$prev_version" >> $GITHUB_OUTPUT
      - name: Validate all files
        run: python .github/validate.py ${{ steps.get_previous_version.outputs.version }}

  upload-release:
    runs-on: ubuntu-latest
    needs: validate-release
    env:
      MOD_UPLOAD_API_KEY: ${{ secrets.MOD_UPLOAD_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create zip
        run: make archive
      - name: Upload new release
        run: python .github/upload.py
